kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/oliver006/rethinkdb_exporter


services:
- name: database
  image: rethinkdb:2
  command: [ rethinkdb, --bind, all ]
  ports:
    - 28015


steps:
  - name: tests
    image: "golang:1.16"
    environment:
      GO111MODULE: on
      RETHINKDB_URI: "database:28015"
    commands:
      - go build .
      - sleep 10   # let the DB test instance come up first
      - make test
      - make checks
    when:
      event:
        - pull_request
        - push
        - tag


  - name: test-docker-build
    image: plugins/docker
    settings:
      tags: "test"
      dockerfile: Dockerfile
      repo: oliver006/rethinkdb_exporter
      target: scratch
      dry_run: true
      build_args:
        - 'TAG=test'
        - 'SHA1=${DRONE_COMMIT_SHA}'
        - 'GOARCH=amd64'
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
    when:
      event:
        - push
        - tag
      branch:
        - master


  - name: release-docker-image-scratch
    image: plugins/docker
    settings:
      tags: "latest,latest-amd64,${DRONE_TAG},${DRONE_TAG}-amd64"
      dockerfile: Dockerfile
      repo: oliver006/rethinkdb_exporter
      target: scratch
      build_args:
        - 'TAG=tst'
        - 'SHA1=${DRONE_COMMIT_SHA}'
        - 'GOARCH=amd64'
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
    when:
      event:
        - tag
        
# got to do this last cause it'll mess up the go.mod / go.sum file and that breaks the docker build
  - name: upload-coverage
    image: "golang:1.16"
    environment:
      GO111MODULE: on
      RETHINKDB_URI: "database:28015"
      COVERALLS_TOKEN:
        from_secret: coveralls-token
    commands:
      - ls -la
      - make upload-coverage
    when:
      event:
        - pull_request
        - push
        - tag
